# Generated by Django 3.2.14 on 2022-11-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=55)),
                ('about', models.TextField()),
                ('types', models.CharField(max_length=100)),
            ],
        ),
    ]
